import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { adminChatId, inlineButton, inlineKeyboard, registerMainMenuItem, requireOwner } from "../toolkit/index.js";
import { recipientIds, removeResource, resources, saveBroadcast, saveResource, storageReady } from "../study-data.js";

registerMainMenuItem({ label: "Admin", data: "admin:login", order: 90 });
const composer = new Composer<Ctx>();
const desk = inlineKeyboard([[inlineButton("Upload resource", "admin:upload"), inlineButton("Manage resources", "admin:resources")],[inlineButton("Send broadcast", "admin:broadcast"), inlineButton("Analytics", "admin:analytics")],[inlineButton("Back to menu", "menu:main")]]);
async function owner(ctx: Ctx): Promise<boolean> { return requireOwner(ctx as unknown as Parameters<typeof requireOwner>[0]); }
composer.callbackQuery("admin:login", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; await ctx.editMessageText("Your StudyCrafter desk is ready.", { reply_markup: desk }); });
composer.callbackQuery("admin:upload", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; if (!(await storageReady(ctx))) { await ctx.reply("Resource storage isn’t set up yet. Add the Worker database binding, then try again."); return; } ctx.session.step = undefined; await ctx.reply("Send the PDF, document, audio, or video you want to add.", { reply_markup: inlineKeyboard([[inlineButton("Cancel", "admin:login")]]) }); });
composer.on("message:document", async (ctx) => { if (!(await owner(ctx))) return; if (!(await storageReady(ctx))) { await ctx.reply("Resource storage isn’t set up yet."); return; } const doc = ctx.message.document; ctx.session.pendingFile = { fileId: doc.file_id, uniqueId: doc.file_unique_id, size: doc.file_size ?? 0, format: (doc.file_name?.split(".").pop() ?? "file").toLowerCase(), type: "document" }; ctx.session.step = "upload-title"; await ctx.reply("Nice. What should students call this resource?", { reply_markup: { force_reply: true, input_field_placeholder: "Try ‘Algebra practice set’" } }); });
composer.on("message:audio", async (ctx) => { if (!(await owner(ctx))) return; const audio = ctx.message.audio; ctx.session.pendingFile = { fileId: audio.file_id, uniqueId: audio.file_unique_id, size: audio.file_size ?? 0, format: "audio", type: "audio" }; ctx.session.step = "upload-title"; await ctx.reply("What should students call this audio resource?", { reply_markup: { force_reply: true, input_field_placeholder: "Type a clear title" } }); });
composer.on("message:video", async (ctx) => { if (!(await owner(ctx))) return; const video = ctx.message.video; ctx.session.pendingFile = { fileId: video.file_id, uniqueId: video.file_unique_id, size: video.file_size ?? 0, format: "video", type: "video" }; ctx.session.step = "upload-title"; await ctx.reply("What should students call this video resource?", { reply_markup: { force_reply: true, input_field_placeholder: "Type a clear title" } }); });
composer.on("message:text", async (ctx, next) => { if (ctx.session.step === "upload-title") { if (!(await owner(ctx))) return; const title = ctx.message.text.trim(); if (title.length < 2 || title.length > 120) { await ctx.reply("Use a clear title between 2 and 120 characters."); return; } ctx.session.pendingTitle = title; ctx.session.step = "upload-metadata"; await ctx.reply("Add class, subject, and access separated by commas. Example: High, Math, free", { reply_markup: { force_reply: true, input_field_placeholder: "High, Math, free" } }); return; }
  if (ctx.session.step === "upload-metadata") { if (!(await owner(ctx))) return; const bits = ctx.message.text.split(",").map((x) => x.trim()); const file = ctx.session.pendingFile; if (!file || bits.length !== 3 || !bits[0] || !bits[1] || !/^(free|premium)$/i.test(bits[2])) { await ctx.reply("Use class, subject, and free or premium. Example: High, Math, free"); return; } const result = await saveResource(ctx, { id: file.uniqueId, title: ctx.session.pendingTitle ?? "Untitled resource", type: file.type, file_id: file.fileId, size: file.size, format: file.format, class_name: bits[0], subject: bits[1], premium_flag: bits[2].toLowerCase() === "premium" }); ctx.session.step = undefined; ctx.session.pendingFile = undefined; ctx.session.pendingTitle = undefined; if (result === "duplicate") { await ctx.reply("That file is already in the library, so I didn’t add it twice."); return; } if (result === "unavailable") { await ctx.reply("I couldn’t save that resource. Try again after storage is set up."); return; } await ctx.reply("Resource added. Students can find it in Browse now."); const admin = adminChatId(ctx as unknown as { env?: Record<string, unknown> }); if (admin) { try { await ctx.api.sendMessage(admin, "A new StudyCrafter resource is ready for students."); } catch { /* A blocked or unavailable owner chat must not undo the upload. */ } } return; }
  if (ctx.session.step === "broadcast-message") { if (!(await owner(ctx))) return; const message = ctx.message.text.trim(); const segment = ctx.session.pendingBroadcastSegment; if (!segment || !message || message.length > 1000) { await ctx.reply("Write a message up to 1,000 characters."); return; } const saved = await saveBroadcast(ctx, segment, message); if (!saved) { await ctx.reply("Broadcast storage isn’t ready yet. Try again after storage is set up."); return; } const recipients = await recipientIds(ctx, segment); let delivered = 0; for (let i = 0; i < recipients.length; i += 25) { await Promise.all(recipients.slice(i, i + 25).map(async (id) => { try { await ctx.api.sendMessage(id, message); delivered++; } catch { /* Users can block a bot; continue with everyone else. */ } })); } ctx.session.step = undefined; ctx.session.pendingBroadcastSegment = undefined; await ctx.reply(`Broadcast sent to ${delivered} learner${delivered === 1 ? "" : "s"}.`); return; }
  return next(); });
composer.callbackQuery("admin:broadcast", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; await ctx.editMessageText("Choose who should receive your study update.", { reply_markup: inlineKeyboard([[inlineButton("All learners", "broadcast:all"), inlineButton("Premium learners", "broadcast:premium")],[inlineButton("Back", "admin:login")]]) }); });
composer.callbackQuery(/^broadcast:(all|premium)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; ctx.session.step = "broadcast-message"; ctx.session.pendingBroadcastSegment = ctx.match[1] as "all" | "premium"; await ctx.reply("Write the update you want to preview and send.", { reply_markup: { force_reply: true, input_field_placeholder: "Share a helpful study update" } }); });
composer.callbackQuery("admin:analytics", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const learners = await recipientIds(ctx, "all"); const premium = await recipientIds(ctx, "premium"); await ctx.editMessageText(`You have ${learners.length} learner${learners.length === 1 ? "" : "s"}, including ${premium.length} premium learner${premium.length === 1 ? "" : "s"}.`, { reply_markup: desk }); });
composer.callbackQuery("admin:resources", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const items = await resources(ctx); if (!items.length) { await ctx.editMessageText("No resources yet — upload one to build your library.", { reply_markup: desk }); return; } await ctx.editMessageText("Choose a resource to remove from the library.", { reply_markup: inlineKeyboard([...items.slice(0, 20).map((item) => [inlineButton(item.title, `admin:resource:${item.id}`)]), [inlineButton("Back", "admin:login")]]) }); });
composer.callbackQuery(/^admin:resource:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; await ctx.editMessageText("Remove this resource from student browse and downloads?", { reply_markup: inlineKeyboard([[inlineButton("Remove resource", `admin:remove:${ctx.match[1]}`), inlineButton("Cancel", "admin:resources")]]) }); });
composer.callbackQuery(/^admin:remove:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const removed = await removeResource(ctx, ctx.match[1]); await ctx.editMessageText(removed ? "Resource removed from the library." : "I couldn’t remove that resource. Try again in a moment.", { reply_markup: desk }); });
export default composer;
